name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Brakeman
        run: gem install brakeman

      - name: Run Brakeman (static analysis for Rails)
        run: brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Rubocop
        run: gem install rubocop

      - name: Run Rubocop (lint Ruby code)
        run: rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Ensure that Rails is installed and bin/rails exists
      - name: Install Rails and dependencies
        run: |
          gem install rails
          bundle install

      # Set executable permissions for bin/rails
      - name: Set execute permissions for bin/rails
        run: chmod +x bin/rails

      # Create the database and run migrations
      - name: Set up database (SQLite)
        run: |
          bin/rails db:create
          bin/rails db:migrate RAILS_ENV=test  # Ensure migrations are applied using bin/rails

      # Run the tests
      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails test
