name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Brakeman 7.0.2
        run: |
          gem install brakeman -v 7.0.2  # Ensure brakeman 7.0.2 is installed

      - name: Make Brakeman executable
        run: |
          chmod +x bin/brakeman  # Ensure brakeman is executable

      - name: Run Brakeman (static analysis for Rails)
        run: |
          if [ -f bin/brakeman ]; then
            ruby bin/brakeman --no-pager  # Use ruby to execute brakeman correctly
          else
            echo "Brakeman not installed. Skipping scan."
          fi
