name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Brakeman
        run: gem install brakeman

      - name: Run Brakeman (static analysis for Rails)
        run: brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Rubocop
        run: gem install rubocop

      - name: Run Rubocop (lint Ruby code)
        run: rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Install Rails and SQLite3 dependencies
      - name: Install Rails and SQLite3 dependencies
        run: |
          gem install rails
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y

      # Install bundle dependencies
      - name: Install dependencies
        run: bundle install

      # Ensure bin/rails is executable
      - name: Make bin/rails executable
        run: chmod +x bin/rails

      # Set up database (SQLite) and apply migrations
      - name: Set up database (SQLite)
        run: |
          bundle exec rails db:create
          bundle exec bin/rails db:migrate  # Ensure migrations are applied

      # Run the tests
      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails test
