name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Brakeman
        run: gem install brakeman

      - name: Run Brakeman (static analysis for Rails)
        run: brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Rubocop
        run: gem install rubocop

      - name: Run Rubocop (lint Ruby code)
        run: rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Install SQLite3 and dependencies
      - name: Install dependencies and SQLite3
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y
          bundle install

      # Ensure bin/rails is executable
      - name: Ensure bin/rails is executable
        run: chmod +x bin/rails

      # Set up the database and apply migrations
      - name: Set up database (SQLite) and apply migrations
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate RAILS_ENV=test

      # Run tests
      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}  # Using the SSH key named 'SSHKEY' from GitHub secrets

      - name: Deploy to EC2
        run: |
              ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-219-157-142.compute-1.amazonaws.com "cd ~/DevOps-sec-crud && git pull origin main && bundle install && rails db:migrate RAILS_ENV=production"
        env:
          EC2_HOST: ec2-13-219-157-142.compute-1.amazonaws.com  # Your EC2 instance DNS
