name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Brakeman (static analysis for Rails)
        run: |
          chmod +x bin/brakeman  # This ensures brakeman has executable permissions
          if [ -f bin/brakeman ]; then
            bin/brakeman --no-pager
          else
            echo "Brakeman not installed. Skipping scan."
          fi

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Importmap Audit
        run: |
          if [ -f bin/importmap ]; then
            bin/importmap audit
          else
            echo "Importmap not found. Skipping JS audit."
          fi

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Rubocop (lint Ruby code)
        run: |
          if [ -f bin/rubocop ]; then
            bin/rubocop -f github
          else
            echo "Rubocop not found. Skipping lint."
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare Test DB & Run Tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bin/rails test
          bin/rails test:system

      - name: Upload screenshots from failed system tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore
